[package]
name = "yaml-datastore"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
thiserror = "2.0.12"

[lints.rust]
missing_docs = "warn"

[lints.clippy]
unwrap_used = "warn"
pedantic = "warn"
